feat(shell): adding additional aliases
Signed-off-by: Bozhidar Dryanovski <bozhidar.dryanovski@gmail.com>

diff --git a/packages/shell/files/zshrc b/packages/shell/files/zshrc
--- a/packages/shell/files/zshrc
+++ b/packages/shell/files/zshrc
@@ -5,7 +5,6 @@ if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]
   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
 fi
 
-
 # Path to your oh-my-zsh installation.
 export ZSH=/Users/bdryanovski/.oh-my-zsh
 
@@ -130,7 +129,6 @@ source "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
 #
 source "$ZSH_CUSTOM/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
 
-
 #
 # User configuration
 # New Alias
@@ -142,6 +140,160 @@ alias getNodeSize='find . -name "node_modules" -type d -prune -print | xargs du 
 alias ll="exa -a -l --no-user --no-time --git -s type --icons"
 alias l="exa -a -s type --icons"
 
+# Usefull stuff for presentation and seeing dotfiles
+alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
+alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
+alias showall='defaults write com.apple.finder AppleShowAllFiles YES && killall Finder'
+alias hideall='defaults write com.apple.finder AppleShowAllFiles NO && killall Finder'
+
+# Get rid of those pesky .DS_Store files recursively
+alias dsclean='find . -type f -name .DS_Store -print0 | xargs -0 rm'
+
+# Download something
+function download(){
+  curl -O "$1"
+}
+
+alias dl=download
+
+# archive file or folder
+function compress() {
+  dirPriorToExe=`pwd`
+  dirName=`dirname $1`
+  baseName=`basename $1`
+
+  if [ -f $1 ] ; then
+    echo "It was a file change directory to $dirName"
+    cd $dirName
+    case $2 in
+      tar.bz2)
+        tar cjf $baseName.tar.bz2 $baseName
+        ;;
+      tar.gz)
+        tar czf $baseName.tar.gz $baseName
+        ;;
+      gz)
+        gzip $baseName
+        ;;
+      tar)
+        tar -cvvf $baseName.tar $baseName
+        ;;
+      zip)
+        zip -r $baseName.zip $baseName
+        ;;
+      *)
+        echo "Method not passed compressing using tar.bz2"
+        tar cjf $baseName.tar.bz2 $baseName
+        ;;
+    esac
+    echo "Back to Directory $dirPriorToExe"
+    cd $dirPriorToExe
+  else
+    if [ -d $1 ] ; then
+      echo "It was a Directory change directory to $dirName"
+      cd $dirName
+      case $2 in
+        tar.bz2)
+          tar cjf $baseName.tar.bz2 $baseName
+          ;;
+        tar.gz)
+          tar czf $baseName.tar.gz $baseName
+          ;;
+        gz)
+          gzip -r $baseName
+          ;;
+        tar)
+          tar -cvvf $baseName.tar $baseName
+          ;;
+        zip)
+          zip -r $baseName.zip $baseName
+          ;;
+        *)
+          echo "Method not passed compressing using tar.bz2"
+          tar cjf $baseName.tar.bz2 $baseName
+          ;;
+      esac
+      echo "Back to Directory $dirPriorToExe"
+      cd $dirPriorToExe
+    else
+      echo "'$1' is not a valid file/folder"
+    fi
+  fi
+  echo "Done"
+  echo "###########################################"
+}
+
+# Extract archives - use: extract <file>
+# Based on http://dotfiles.org/~pseup/.bashrc
+function extract() {
+  local remove_archive
+  local success
+  local file_name
+  local extract_dir
+
+  if (( $# == 0 )); then
+    echo "Usage: extract [-option] [file ...]"
+    echo
+    echo Options:
+    echo "    -r, --remove    Remove archive."
+  fi
+
+  remove_archive=1
+  if [[ "$1" == "-r" ]] || [[ "$1" == "--remove" ]]; then
+    remove_archive=0
+    shift
+  fi
+
+  while (( $# > 0 )); do
+    if [[ ! -f "$1" ]]; then
+      echo "extract: '$1' is not a valid file" 1>&2
+      shift
+      continue
+    fi
+
+    success=0
+    file_name="$( basename "$1" )"
+    extract_dir="$( echo "$file_name" | sed "s/\.${1##*.}//g" )"
+    case "$1" in
+      (*.tar.gz|*.tgz) [ -z $commands[pigz] ] && tar zxvf "$1" || pigz -dc "$1" | tar xv ;;
+      (*.tar.bz2|*.tbz|*.tbz2) tar xvjf "$1" ;;
+      (*.tar.xz|*.txz) tar --xz --help &> /dev/null \
+        && tar --xz -xvf "$1" \
+        || xzcat "$1" | tar xvf - ;;
+    (*.tar.zma|*.tlz) tar --lzma --help &> /dev/null \
+      && tar --lzma -xvf "$1" \
+      || lzcat "$1" | tar xvf - ;;
+  (*.tar) tar xvf "$1" ;;
+  (*.gz) [ -z $commands[pigz] ] && gunzip "$1" || pigz -d "$1" ;;
+  (*.bz2) bunzip2 "$1" ;;
+  (*.xz) unxz "$1" ;;
+  (*.lzma) unlzma "$1" ;;
+  (*.Z) uncompress "$1" ;;
+  (*.zip|*.war|*.jar|*.sublime-package) unzip "$1" -d $extract_dir ;;
+  (*.rar) unrar x -ad "$1" ;;
+  (*.7z) 7za x "$1" ;;
+  (*.deb)
+    mkdir -p "$extract_dir/control"
+    mkdir -p "$extract_dir/data"
+    cd "$extract_dir"; ar vx "../${1}" > /dev/null
+    cd control; tar xzvf ../control.tar.gz
+    cd ../data; tar xzvf ../data.tar.gz
+    cd ..; rm *.tar.gz debian-binary
+    cd ..
+    ;;
+  (*)
+    echo "extract: '$1' cannot be extracted" 1>&2
+    success=1
+    ;;
+      esac
+
+      (( success = $success > 0 ? $success : $? ))
+      (( $success == 0 )) && (( $remove_archive == 0 )) && rm "$1"
+      shift
+  done
+}
+
+alias x=extract
 
 #
 # JavaScript
@@ -190,5 +342,5 @@ export PATH=$PATH:$GOROOT/bin
 #
 # NeoVide
 #
-# Need to be installed and configure 
+# Need to be installed and configure
 alias neovide=~/Github/neovide/target/release/neovide --multigrid
